name: CI

on:
  push:
    branches: [main]
  pull_request:
  
  
jobs:
  hello:
    runs-on: ubuntu-latest
    steps: 
      - name: Afficher un message 
        run : echo "Bonjour debuops Github Action!!!!"
  
